### ISSUE TITLE
Can't figure out the CLI syntax to get downloading all episodes to work

### ISSUE THREAD

**Issue by feoh** [jakkso/Podd#5]
```
88e9fe75fb6a:~ cpatti$ podd dl  --all
Usage: podd dl [OPTIONS]
Try 'podd dl --help' for help.

Error: No such option: --all
```

**Comment by awfki** [comment]
I know this is over a year old but...  

It's `podd add --catalog URL` and then when you do `podd dl` it will pull them all.  So only works on a new feed.

_edit because it's not --all_
